### ISSUE TITLE
resolvePackageRoot logic is incorrect

### ISSUE THREAD

**Issue by NullVoxPopuli** [ember-tooling/ember-language-server#414]
![image](https://github.com/user-attachments/assets/0af4f140-2156-4615-9fa8-bd7524f5cf35)

This will traverse back to the root of the disk -- and we want to stop at a git-boundary.

I guess, if there is a git boundary -- not every project will use git

**Comment by lifeart** [comment]
It's expected behaviour, because `packageRoot` is not equal to `projectRoot`, npm may lookup till user homedir for global node_modules.

It’s because we have to work in virtual env, like browsers, we can’t rely on project root dir, for monorepo case package may be under project (on top-level node-modules)

**Comment by NullVoxPopuli** [comment]
I think, development wise, i way need to work in tmp then! Lol

**Comment by NullVoxPopuli** [comment]
how do you do that locally? in stackblitz-based things, perf seems kinda slow 😅

**Comment by lifeart** [comment]
@NullVoxPopuli no web containers on my side, just crossing my fingers once doing npm install! 😂
